// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzbomhywksfbpeyhhqda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6Ym9taHl3a3NmYnBleWhocWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNjcyNDQsImV4cCI6MjA2NDY0MzI0NH0.fBzopkCuHBY_s4kOCruA1I6hh7Mi6DYfZsPhHTmmxng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);